### ISSUE TITLE
apex import error: "ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)"

### ISSUE THREAD

**Issue by cameron-a-johnson** [PierfrancescoArdino/SGINet#3]
Issue:
Just that there's no documented install process. After just "pip installing" all imports, running main.py gives the following traceback:
```
Traceback (most recent call last):                                                                                                                                                
  File "main.py", line 21, in <module>                                                                                                                                            
    from apex.parallel import DistributedDataParallel as DDP                                                                                                                      
  File "/home/cameron/.local/conda/envs/py38/lib/python3.8/site-packages/apex/__init__.py", line 13, in <module>                                                                  
    from pyramid.session import UnencryptedCookieSessionFactoryConfig                                                                                                             
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)   
```                                                              

Fix:
Install Nvidia's apex, as the Pypi apex is unrelated.
```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./
```

All other dependency installs were obvious, but I personally hadn't used this DDP library before.

**Comment by PierfrancescoArdino** [comment]
Yes, if you want to install using conda just use 

`conda install -c conda-forge nvidia-apex`

Apex refers to nvidia-apex, not to pypi-apex :D

**Comment by cameron-a-johnson** [comment]
Oh cool! Thanks.
