### ISSUE TITLE
opt.no_ganTV_loss not defined in model file

### ISSUE THREAD

**Issue by cameron-a-johnson** [PierfrancescoArdino/SGINet#5]
Running `src/script/train_paper_cityscapes.sh`, I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 586, in <module>            
    train(None, opt)                               
  File "main.py", line 98, in train
    model = SGINetModel(opt)                       
  File "/home/cameron/code/overhead-object-inpainting/src/models/sgi_model.py", line 187, in __init__
    not self.opt.no_ganTV_loss,
```

When I comment out [that line](https://github.com/PierfrancescoArdino/SGINet/blob/main/src/models/sgi_model.py#L187), the code seems to train successfully!

**Comment by cameron-a-johnson** [comment]
Closing this issue, per your fix in which the line is removed in the latest version
